# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"&\n\x10SubscribeRequest\x12\x12\n\nstream_ids\x18\x01 \x03(\t\"6\n\x04\x42\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"\xe3\x01\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x1d\n\x04\x62\x62ox\x18\x04 \x01(\x0b\x32\x0f.inference.BBox\x12\x10\n\x08track_id\x18\x05 \x01(\x03\x12\x38\n\nattributes\x18\x06 \x03(\x0b\x32$.inference.Detection.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x01\n\x0e\x44\x65tectionFrame\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_ts\x18\x02 \x01(\x01\x12\x10\n\x08infer_ts\x18\x03 \x01(\x01\x12\x12\n\nlatency_ms\x18\x04 \x01(\x01\x12\x10\n\x08model_id\x18\x05 \x01(\t\x12\x11\n\tframe_seq\x18\x06 \x01(\x04\x12(\n\ndetections\x18\x07 \x03(\x0b\x32\x14.inference.Detection2Y\n\x10InferenceService\x12\x45\n\tSubscribe\x12\x1b.inference.SubscribeRequest\x1a\x19.inference.DetectionFrame0\x01\x42\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_DETECTION_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SUBSCRIBEREQUEST']._serialized_start=30
  _globals['_SUBSCRIBEREQUEST']._serialized_end=68
  _globals['_BBOX']._serialized_start=70
  _globals['_BBOX']._serialized_end=124
  _globals['_DETECTION']._serialized_start=127
  _globals['_DETECTION']._serialized_end=354
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_start=305
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_end=354
  _globals['_DETECTIONFRAME']._serialized_start=357
  _globals['_DETECTIONFRAME']._serialized_end=527
  _globals['_INFERENCESERVICE']._serialized_start=529
  _globals['_INFERENCESERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
