// Package main is the infer-server management sidecar.
//
//	@title			infer-server Management API
//	@version		1.0
//	@description	HTTP management API. All write operations are forwarded to the C++ engine via Unix domain socket.
//	@description
//	@description	Protected endpoints require the header: Authorization: Bearer <INFER_API_KEY>
//	@BasePath		/
//
//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@description				Type "Bearer" followed by a space and your API key.
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "infer-tools/infer-server/docs" // generated by swag init
)

var (
	socketPath = envOr("INFER_SOCKET", "/var/run/infer.sock")
	listenAddr = envOr("INFER_SERVER_ADDR", ":8080")
	apiKey     = os.Getenv("INFER_API_KEY")
	statePath  = envOr("INFER_STATE_FILE", "/var/lib/infer-server/state.json")
	store      *Store
)

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func corsMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Authorization, Content-Type")
		if c.Request.Method == http.MethodOptions {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	}
}

func authMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		bearer := c.GetHeader("Authorization")
		if !strings.HasPrefix(bearer, "Bearer ") || strings.TrimPrefix(bearer, "Bearer ") != apiKey {
			c.AbortWithStatusJSON(http.StatusUnauthorized, ErrorResponse{
				Status:  "error",
				Code:    "unauthorized",
				Message: "missing or invalid API key",
			})
			return
		}
		c.Next()
	}
}

// callFn is the engine communication function; replaceable in tests.
var callFn = func(cmd map[string]any) (map[string]any, error) {
	conn, err := net.Dial("unix", socketPath)
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	data, err := json.Marshal(cmd)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}
	fmt.Fprintf(conn, "%s\n", data)

	var resp map[string]any
	if err := json.NewDecoder(bufio.NewReader(conn)).Decode(&resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func call(cmd map[string]any) (map[string]any, error) { return callFn(cmd) }

func engineUnavailable(c *gin.Context, err error) {
	c.String(http.StatusServiceUnavailable, err.Error())
}

// handleHealthz godoc
//
//	@Summary	Health check
//	@Tags		health
//	@Produce	plain
//	@Success	200	{string}	string	"OK"
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/healthz [get]
func handleHealthz(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "health"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] != "ok" {
		c.JSON(http.StatusServiceUnavailable, resp)
		return
	}
	c.String(http.StatusOK, "OK")
}

// handleMetrics godoc
//
//	@Summary	Prometheus metrics
//	@Tags		health
//	@Produce	plain
//	@Success	200	{string}	string	"Prometheus text format"
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/metrics [get]
func handleMetrics(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "metrics"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	c.Header("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
	if m, ok := resp["data"].(string); ok {
		c.String(http.StatusOK, m)
	}
}

// handleListSources godoc
//
//	@Summary	List sources
//	@Tags		sources
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Success	200	{array}		SourceInfo
//	@Failure	401	{object}	ErrorResponse
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/sources [get]
func handleListSources(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "list_sources"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	c.JSON(http.StatusOK, resp["data"])
}

// handleAddSource godoc
//
//	@Summary	Add a source
//	@Tags		sources
//	@Accept		json
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		body	body		SourceCreate	true	"Source definition"
//	@Success	201		{object}	OkResponse
//	@Failure	400		{object}	ErrorResponse
//	@Failure	401		{object}	ErrorResponse
//	@Failure	503		{string}	string	"engine unreachable"
//	@Router		/sources [post]
func handleAddSource(c *gin.Context) {
	var body SourceCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.String(http.StatusBadRequest, "invalid JSON body")
		return
	}
	m := mustToMap(body)
	m["cmd"] = "add_source"
	resp, err := call(m)
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SaveSource(body)
	}
	code := http.StatusCreated
	if resp["status"] != "ok" {
		code = http.StatusBadRequest
	}
	c.JSON(code, resp)
}

// handleRemoveSource godoc
//
//	@Summary	Remove a source
//	@Tags		sources
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id	path		string	true	"Source ID"
//	@Success	200	{object}	OkResponse
//	@Failure	401	{object}	ErrorResponse
//	@Failure	404	{object}	ErrorResponse
//	@Failure	409	{object}	ErrorResponse	"source is in use by a task"
//	@Failure	503	{string}	string			"engine unreachable"
//	@Router		/sources/{id} [delete]
func handleRemoveSource(c *gin.Context) {
	callDelete(c, "remove_source", func(id string) { _ = store.DeleteSource(id) })
}

// handleListPipelines godoc
//
//	@Summary	List pipelines
//	@Tags		pipelines
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Success	200	{array}		PipelineInfo
//	@Failure	401	{object}	ErrorResponse
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/pipelines [get]
func handleListPipelines(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "list_pipelines"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	c.JSON(http.StatusOK, resp["data"])
}

// handleAddPipeline godoc
//
//	@Summary	Add a pipeline
//	@Tags		pipelines
//	@Accept		json
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		body	body		PipelineCreate	true	"Pipeline definition"
//	@Success	201		{object}	OkResponse
//	@Failure	400		{object}	ErrorResponse
//	@Failure	401		{object}	ErrorResponse
//	@Failure	503		{string}	string	"engine unreachable"
//	@Router		/pipelines [post]
func handleAddPipeline(c *gin.Context) {
	var body PipelineCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.String(http.StatusBadRequest, "invalid JSON body")
		return
	}
	m := mustToMap(body)
	m["cmd"] = "add_pipeline"
	resp, err := call(m)
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SavePipeline(body)
	}
	code := http.StatusCreated
	if resp["status"] != "ok" {
		code = http.StatusBadRequest
	}
	c.JSON(code, resp)
}

// handleUpdatePipeline godoc
//
//	@Summary	Update a pipeline
//	@Tags		pipelines
//	@Accept		json
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id		path		string			true	"Pipeline ID"
//	@Param		body	body		PipelineCreate	true	"Pipeline definition"
//	@Success	200		{object}	OkResponse
//	@Failure	400		{object}	ErrorResponse
//	@Failure	401		{object}	ErrorResponse
//	@Failure	404		{object}	ErrorResponse
//	@Failure	409		{object}	ErrorResponse	"pipeline is in use by a task"
//	@Failure	503		{string}	string			"engine unreachable"
//	@Router		/pipelines/{id} [put]
func handleUpdatePipeline(c *gin.Context) {
	id := c.Param("id")
	var body PipelineCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.String(http.StatusBadRequest, "invalid JSON body")
		return
	}
	body.ID = id
	m := mustToMap(body)
	m["cmd"] = "update_pipeline"
	resp, err := call(m)
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SavePipeline(body)
	}
	code := http.StatusOK
	if resp["status"] != "ok" {
		code = http.StatusBadRequest
	}
	c.JSON(code, resp)
}

// handleRemovePipeline godoc
//
//	@Summary	Remove a pipeline
//	@Tags		pipelines
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id	path		string	true	"Pipeline ID"
//	@Success	200	{object}	OkResponse
//	@Failure	401	{object}	ErrorResponse
//	@Failure	404	{object}	ErrorResponse
//	@Failure	409	{object}	ErrorResponse	"pipeline is in use by a task"
//	@Failure	503	{string}	string			"engine unreachable"
//	@Router		/pipelines/{id} [delete]
func handleRemovePipeline(c *gin.Context) {
	callDelete(c, "remove_pipeline", func(id string) { _ = store.DeletePipeline(id) })
}

// handleListModels godoc
//
//	@Summary	List loaded models
//	@Tags		models
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Success	200	{array}		ModelInfo
//	@Failure	401	{object}	ErrorResponse
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/models [get]
func handleListModels(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "list_models"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	c.JSON(http.StatusOK, resp["data"])
}

// handleLoadModel godoc
//
//	@Summary	Load a model
//	@Tags		models
//	@Accept		json
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		body	body		ModelLoad	true	"Model definition"
//	@Success	201		{object}	OkResponse
//	@Failure	400		{object}	ErrorResponse
//	@Failure	401		{object}	ErrorResponse
//	@Failure	503		{string}	string	"engine unreachable"
//	@Router		/models [post]
func handleLoadModel(c *gin.Context) {
	var body ModelLoad
	if err := c.ShouldBindJSON(&body); err != nil {
		c.String(http.StatusBadRequest, "invalid JSON body")
		return
	}
	m := mustToMap(body)
	m["cmd"] = "load_model"
	resp, err := call(m)
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SaveModel(body)
	}
	code := http.StatusCreated
	if resp["status"] != "ok" {
		code = http.StatusBadRequest
	}
	c.JSON(code, resp)
}

// handleUnloadModel godoc
//
//	@Summary	Unload a model
//	@Tags		models
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id	path		string	true	"Model ID"
//	@Success	200	{object}	OkResponse
//	@Failure	401	{object}	ErrorResponse
//	@Failure	404	{object}	ErrorResponse
//	@Failure	409	{object}	ErrorResponse	"model is in use by a running task"
//	@Failure	503	{string}	string			"engine unreachable"
//	@Router		/models/{id} [delete]
func handleUnloadModel(c *gin.Context) {
	callDelete(c, "unload_model", func(id string) { _ = store.DeleteModel(id) })
}

// handleListTasks godoc
//
//	@Summary	List tasks
//	@Tags		tasks
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Success	200	{array}		TaskInfo
//	@Failure	401	{object}	ErrorResponse
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/tasks [get]
func handleListTasks(c *gin.Context) {
	resp, err := call(map[string]any{"cmd": "list_tasks"})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	c.JSON(http.StatusOK, resp["data"])
}

// handleAddTask godoc
//
//	@Summary		Add a task
//	@Description	Creates a task binding a source to a pipeline. Starts in stopped state; use POST /tasks/{id}/start to activate.
//	@Tags			tasks
//	@Accept			json
//	@Produce		json
//	@Security		ApiKeyAuth
//	@Param			body	body		TaskCreate	true	"Task definition"
//	@Success		201		{object}	OkResponse
//	@Failure		400		{object}	ErrorResponse
//	@Failure		401		{object}	ErrorResponse
//	@Failure		503		{string}	string	"engine unreachable"
//	@Router			/tasks [post]
func handleAddTask(c *gin.Context) {
	var body TaskCreate
	if err := c.ShouldBindJSON(&body); err != nil {
		c.String(http.StatusBadRequest, "invalid JSON body")
		return
	}
	m := mustToMap(body)
	m["cmd"] = "add_task"
	resp, err := call(m)
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SaveTask(body)
	}
	code := http.StatusCreated
	if resp["status"] != "ok" {
		code = http.StatusBadRequest
	}
	c.JSON(code, resp)
}

// handleRemoveTask godoc
//
//	@Summary	Remove a task
//	@Tags		tasks
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id	path		string	true	"Task ID"
//	@Success	200	{object}	OkResponse
//	@Failure	401	{object}	ErrorResponse
//	@Failure	404	{object}	ErrorResponse
//	@Failure	503	{string}	string	"engine unreachable"
//	@Router		/tasks/{id} [delete]
func handleRemoveTask(c *gin.Context) {
	callDelete(c, "remove_task", func(id string) { _ = store.DeleteTask(id) })
}

// handleTaskAction godoc
//
//	@Summary	Start or stop a task
//	@Tags		tasks
//	@Produce	json
//	@Security	ApiKeyAuth
//	@Param		id		path		string	true	"Task ID"
//	@Param		action	path		string	true	"Action"	Enums(start, stop)
//	@Success	200		{object}	OkResponse
//	@Failure	401		{object}	ErrorResponse
//	@Failure	404		{object}	ErrorResponse
//	@Failure	503		{string}	string	"engine unreachable"
//	@Router		/tasks/{id}/{action} [post]
func handleTaskAction(c *gin.Context) {
	id := c.Param("id")
	action := c.Param("action")
	if action != "start" && action != "stop" {
		c.Status(http.StatusNotFound)
		return
	}
	resp, err := call(map[string]any{"cmd": action + "_task", "id": id})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" {
		_ = store.SetTaskRunning(id, action == "start")
	}
	code := http.StatusOK
	if resp["status"] != "ok" {
		code = http.StatusNotFound
	}
	c.JSON(code, resp)
}

func callDelete(c *gin.Context, cmd string, onSuccess func(id string)) {
	id := c.Param("id")
	resp, err := call(map[string]any{"cmd": cmd, "id": id})
	if err != nil {
		engineUnavailable(c, err)
		return
	}
	if resp["status"] == "ok" && onSuccess != nil {
		onSuccess(id)
	}
	code := http.StatusOK
	if resp["status"] != "ok" {
		if resp["code"] == "in_use" {
			code = http.StatusConflict
		} else {
			code = http.StatusNotFound
		}
	}
	c.JSON(code, resp)
}

func main() {
	if apiKey == "" {
		fmt.Fprintln(os.Stderr, "WARNING: INFER_API_KEY not set; management endpoints are unprotected")
	}

	var err error
	store, err = NewStore(statePath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "state store init:", err)
		os.Exit(1)
	}
	go func() {
		if err := replayState(store.Snapshot(), callFn, 30, 2*time.Second); err != nil {
			fmt.Fprintln(os.Stderr, "WARNING: state replay incomplete:", err)
		}
	}()

	r := gin.Default()
	r.Use(corsMiddleware())

	// Public: health probe, metrics scrape, API docs.
	r.GET("/healthz", handleHealthz)
	r.GET("/metrics", handleMetrics)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Protected management endpoints.
	api := r.Group("/")
	if apiKey != "" {
		api.Use(authMiddleware())
	}

	api.GET("/sources", handleListSources)
	api.POST("/sources", handleAddSource)
	api.DELETE("/sources/:id", handleRemoveSource)

	api.GET("/pipelines", handleListPipelines)
	api.POST("/pipelines", handleAddPipeline)
	api.PUT("/pipelines/:id", handleUpdatePipeline)
	api.DELETE("/pipelines/:id", handleRemovePipeline)

	api.GET("/models", handleListModels)
	api.POST("/models", handleLoadModel)
	api.DELETE("/models/:id", handleUnloadModel)

	api.GET("/tasks", handleListTasks)
	api.POST("/tasks", handleAddTask)
	api.DELETE("/tasks/:id", handleRemoveTask)
	api.POST("/tasks/:id/:action", handleTaskAction)

	fmt.Printf("infer-server listening on %s (socket: %s)\n", listenAddr, socketPath)
	if err := r.Run(listenAddr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
