// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "Prometheus text format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "List loaded models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/infer-server.ModelInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Load a model",
                "parameters": [
                    {
                        "description": "Model definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infer-server.ModelLoad"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/models/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Unload a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "model is in use by a running task",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pipelines": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "List pipelines",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/infer-server.PipelineInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Add a pipeline",
                "parameters": [
                    {
                        "description": "Pipeline definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infer-server.PipelineCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pipelines/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Remove a pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "pipeline is in use by a task",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/infer-server.SourceInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Add a source",
                "parameters": [
                    {
                        "description": "Source definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infer-server.SourceCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sources/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Remove a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "source is in use by a task",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "List tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/infer-server.TaskInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a task binding a source to a pipeline. Starts in stopped state; use POST /tasks/{id}/start to activate.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Add a task",
                "parameters": [
                    {
                        "description": "Task definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/infer-server.TaskCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Remove a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/{action}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Start or stop a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "start",
                            "stop"
                        ],
                        "type": "string",
                        "description": "Action",
                        "name": "action",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/infer-server.OkResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/infer-server.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "engine unreachable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "infer-server.EdgeConfig": {
            "type": "object",
            "required": [
                "from",
                "to"
            ],
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "drop_policy": {
                    "type": "string",
                    "enum": [
                        "block",
                        "drop_oldest",
                        "drop_newest"
                    ]
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "infer-server.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "in_use"
                },
                "message": {
                    "type": "string",
                    "example": "source in use by a task: cam0"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "infer-server.InputShape": {
            "type": "object",
            "properties": {
                "c": {
                    "type": "integer",
                    "example": 3
                },
                "h": {
                    "type": "integer",
                    "example": 640
                },
                "w": {
                    "type": "integer",
                    "example": 640
                }
            }
        },
        "infer-server.ModelInfo": {
            "type": "object",
            "properties": {
                "backend": {
                    "type": "string"
                },
                "batch_size": {
                    "type": "integer"
                },
                "class_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "conf_thresh": {
                    "type": "number"
                },
                "device_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "input_shape": {
                    "type": "string",
                    "example": "3x640x640"
                },
                "instance_count": {
                    "type": "integer"
                },
                "max_queue_delay_us": {
                    "type": "integer"
                },
                "model_type": {
                    "type": "string",
                    "enum": [
                        "detector",
                        "classifier"
                    ]
                },
                "nms_thresh": {
                    "type": "number"
                },
                "num_classes": {
                    "type": "integer"
                },
                "preferred_batch_sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "infer-server.ModelLoad": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "backend": {
                    "type": "string",
                    "enum": [
                        "cpu",
                        "trt",
                        "ascend"
                    ]
                },
                "batch_size": {
                    "type": "integer"
                },
                "class_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "conf_thresh": {
                    "type": "number"
                },
                "device_id": {
                    "type": "integer"
                },
                "engine_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_shape": {
                    "$ref": "#/definitions/infer-server.InputShape"
                },
                "instance_count": {
                    "type": "integer"
                },
                "max_queue_delay_us": {
                    "type": "integer"
                },
                "model_type": {
                    "type": "string",
                    "enum": [
                        "detector",
                        "classifier"
                    ]
                },
                "nms_thresh": {
                    "type": "number"
                },
                "num_classes": {
                    "type": "integer"
                },
                "onnx_path": {
                    "type": "string"
                },
                "preferred_batch_sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "version": {
                    "type": "string",
                    "enum": [
                        "v5",
                        "v8",
                        "v11",
                        "v26"
                    ]
                }
            }
        },
        "infer-server.OkResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "cam0"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "infer-server.PipelineCreate": {
            "type": "object",
            "required": [
                "id",
                "nodes"
            ],
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/infer-server.EdgeConfig"
                    }
                },
                "id": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/infer-server.StageConfig"
                    }
                }
            }
        },
        "infer-server.PipelineEdgeInfo": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "drop_policy": {
                    "type": "string",
                    "enum": [
                        "block",
                        "drop_oldest",
                        "drop_newest"
                    ]
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "infer-server.PipelineInfo": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/infer-server.PipelineEdgeInfo"
                    }
                },
                "id": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/infer-server.PipelineNodeInfo"
                    }
                }
            }
        },
        "infer-server.PipelineNodeInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "with": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "infer-server.SourceCreate": {
            "type": "object",
            "required": [
                "id",
                "url"
            ],
            "properties": {
                "degraded_threshold": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "max_reconnect_attempts": {
                    "type": "integer"
                },
                "max_reconnect_delay_ms": {
                    "type": "integer"
                },
                "open_timeout_ms": {
                    "type": "integer"
                },
                "read_timeout_ms": {
                    "type": "integer"
                },
                "reconnect_delay_ms": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "infer-server.SourceInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "reconnect_count": {
                    "type": "integer"
                },
                "state": {
                    "type": "string",
                    "enum": [
                        "CONNECTING",
                        "STREAMING",
                        "RECONNECTING",
                        "DEGRADED",
                        "STOPPED"
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "infer-server.StageConfig": {
            "type": "object",
            "required": [
                "id",
                "type"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "with": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "infer-server.TaskCreate": {
            "type": "object",
            "required": [
                "id",
                "pipeline_id",
                "source_id"
            ],
            "properties": {
                "ascend_device_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "sample_fps": {
                    "type": "number"
                },
                "sampling_mode": {
                    "type": "string",
                    "enum": [
                        "frame_count",
                        "time_based"
                    ]
                },
                "source_id": {
                    "type": "string"
                },
                "use_ascend_dvpp": {
                    "type": "boolean"
                },
                "use_hwdec": {
                    "type": "boolean"
                }
            }
        },
        "infer-server.TaskInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "state": {
                    "type": "string",
                    "enum": [
                        "running",
                        "stopped"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer\" followed by a space and your API key.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "infer-server Management API",
	Description:      "HTTP management API. All write operations are forwarded to the C++ engine via Unix domain socket.\n\nProtected endpoints require the header: Authorization: Bearer <INFER_API_KEY>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
